### ISSUE TITLE
Cannot login from nextcloud instance

### ISSUE THREAD

**Issue by DoubleWookie** [nextcloud/integration_mattermost#3] opened 2022-09-22 00:05 UTC
Hello!
I've installed this plugin from the nextcloud's app store in my server, i get the correct setting's page in my instance but when i put in my mattermost address and token as a regular user, i get this popup in nextcloud with the following content:
`Failed to save Mattermost options:

[name of server]

<div id="nojavascript">
<div>
This application requires JavaScript for correct operation. Please <a href="https://www.enable-javascript.com/" target="_blank" rel="noreferrer noopener">enable JavaScript</a> and reload the page. </div>
</div>

[name of server]

Internal Server Error
The server was unable to complete your request.
If this happens again, please send the technical details below to the server administrator.
More details can be found in the server log.

Technical details

Remote Address: [server address]
Request ID: [id]

[name of server] – [nextcloud server slogan]

Skip to main content
Skip to navigation of app
Mattermost integration

If you are allowed to, You can create a personal access token in your Mattermost profile -> Security -> Personal Access Tokens.

You can connect with a personal token OR just with your login/password.
Mattermost instance address
Personal access token`

Any idea what could be wrong?

**Comment by eneiluj** [comment] 2022-10-05 10:23
Hey. Thanks for the bug report. There most likely is an error on the server side. I need the relevant lines in nextcloud.log to understand what happens. Any extra info on your setup can also help.

**Comment by lockdlock** [comment] 2022-10-13 03:24
> Hey. Thanks for the bug report. There most likely is an error on the server side. I need the relevant lines in nextcloud.log to understand what happens. Any extra info on your setup can also help.

Hi, 
After several repeated tests, we found the cause.
It seems that the error occurs if the password policy set in nextcloud is not met.
If the policy is met, the transmission is possible.
It would be easier to understand if a password policy warning screen is displayed instead of a javascript error.

**Comment by julien-nc** [comment] 2022-10-13 10:42
@lockdlock Thanks for the feedback. Your issue is very different from the one of @DoubleWookie.

I just fixed the password policy stuff. The server error message now goes up to the frontend. This will be included in the next release which is coming soonish.

@DoubleWookie I still need the relevant lines in nextcloud.log when authentication fails on your side to understand what happens.

**Comment by kyteinsky** [comment] 2024-01-11 08:40
@DoubleWookie If this is still relevant, consider reopening this issue.

**Closed by kyteinsky** 2024-01-11 08:40 UTC
